# Generated by Django 3.0.4 on 2020-04-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contenr',
            new_name='content',
        ),
    ]
